DROP TABLE IF EXISTS pokemon CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS pokemon_stats CASCADE;
DROP TABLE IF EXISTS ranking CASCADE;
DROP TYPE IF EXISTS event_type;
DROP TYPE IF EXISTS placement_type;